### ISSUE TITLE
I get an error the first time running make on the Typica service

### ISSUE THREAD

**Issue by JedBartlett** [JedBartlett/OrthodoxLiturgics#4]
$ make
/bin/sh: 1: cd: can't cd to out.pentecost-tablet

If I <ctrl> c, the process stops with a dump of several other errors (Shown below)
but running make a second time seems to kick things off without a hitch.

My make foo is not as strong as yours, if you could look into it, I'd appreciate it. Thanks!

<pre><code>
$ make
/bin/sh: 1: cd: can't cd to out.pentecost-tablet
^CTraceback (most recent call last):
make: *** Deleting file 'out.pentecost-tablet/SundayReaderTypica.tex'
  File "/home/jedidiah/lilypond/usr/bin/lilypond-book", line 776, in ?
    main ()
  File "/home/jedidiah/lilypond/usr/bin/lilypond-book", line 759, in main
    chunks = do_file (files[0])
  File "/home/jedidiah/lilypond/usr/bin/lilypond-book", line 634, in do_file
    chunks))
  File "/home/jedidiah/lilypond/usr/bin/lilypond-book", line 630, in process_include
    return do_file (name, included=True)
  File "/home/jedidiah/lilypond/usr/bin/lilypond-book", line 620, in do_file
    do_process_cmd (chunks, input_fullname, global_options)
  File "/home/jedidiah/lilypond/usr/bin/lilypond-book", line 489, in do_process_cmd
    options.formatter, options.lily_output_dir)
  File "/home/jedidiah/lilypond/usr/bin/lilypond-book", line 441, in process_snippets
    logfile)
  File "/home/jedidiah/lilypond/usr/bin/lilypond-book", line 413, in system_in_directory
    ignore_error=global_options.redirect_output)
  File "/home/jedidiah/lilypond/usr/share/lilypond/current/python/lilylib.py", line 222, in subprocess_system
    retval = proc.wait()
  File "/home/jedidiah/lilypond/usr/lib/python2.4/subprocess.py", line 1007, in wait
    pid, sts = os.waitpid(self.pid, 0)
KeyboardInterrupt
Makefile:150: recipe for target 'out.pentecost-tablet/SundayReaderTypica.tex' failed
make: *** [out.pentecost-tablet/SundayReaderTypica.tex] Interrupt
</code></pre>

**Comment by Pafnoutios** [comment]
The error from CD is just the check whether the working directory exists.  I expect those to end up being externally (manually) generated with a CMake based build, so I don't feel highly compelled to suppress that output.

The rest just looks like a normal Python backtrace, probably invoked by ^C.  The lilypond-book program is a python script and it is invoked in quiet mode with the `--loglevel=ERROR` and `--lily-loglevel=ERROR` options.

```
lily_command = lilypond-book --pdf --include=../$(included_music_dir) --loglevel=ERROR --lily-loglevel=ERROR
```

Try waiting longer for lilypond to finish.

**Comment by JedBartlett** [comment]
Yea, I left it running when I left for work, came back and had all the PDFs!
Modifying the Holy God now to add the extra languages, I think I just about
have it.
